# Generated by Django 5.2.12 on 2026-03-17 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}/\\d{5,6}/\\d{2}$', 'Enter valid Registration No. (e.g. IN13/00159/23)')], verbose_name='Registration No.'),
        ),
    ]
